### ISSUE TITLE
2 x *mobxAutorun directive(s) in todos template

### ISSUE THREAD

**Issue by SerkanSipahi** [mobxjs/mobx-angular#62] opened 2018-01-29 09:44 UTC
This is a very simple question for someone who is very familiar with mobx-angular but for me is that not clear at first glance why there are `2 x *mobxAuto directive(s)` in the todos [template](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html) ! 

Questions:
- Because of performance reasons?
- Because of separation the renderings sections?
-- what does this [line](https://github.com/mobxjs/mobx-angular/blob/master/lib/directives/mobx-autorun.directive.ts#L19) do in the mobxAuto directive library ? What they receive, the html section of [html-section](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html#L8-L20) and [html-footer](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html#L21-L37) or the whole component [template](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html#L1-L38)? 

- when it is recommended to use several *mobxAuto(s)

**Comment by SerkanSipahi** [comment] 2018-01-29 11:41
After some investigations i found out that https://github.com/mobxjs/mobx-angular/blob/master/lib/directives/mobx-autorun.directive.ts#L19 will called only one time no matter how many times it is declared in the template. I thought (as i said above) the templateRef inside of #L19 is for each html section.

Sorry im so confused :(

**Comment by adamkleingit** [comment] 2018-01-29 13:41
The best way would have been to split this into 2 components and not keep everything under AppComponent - I think this should be solved to avoid further confusion

**Comment by SvenSchoene** [comment] 2018-01-29 14:13
Wait, just to get it right: it's never a good idea to have multiple containers in a component templates marked with the `*mobxAutorun* directive?

I'd hypothesize that sometimes it might actually be a still-ok level of abstraction to not break down a component even smaller just for the "autorun-zones". E.g., maybe there's a long form and for performance reasons it might make sense to split the "autorun zones" (what's the correct wording for this? HTML containers tagged with the `*mobxAutorun`-directive?) up, doesn't it?`

Wait, does it, though?
A practical example:
```
<section class="longListOfCountriesAndStatesAndCities" *mobxAutorun>
  <div *ngFor="let obj of allCountriesStatesCitiesInTheWorld">...</div>
</section>

<section class="longListOfUsersLikeReallyLong" *mobxAutorun>
  <div *ngFor="let user of allFacebookUsersInTheWholeSystem">...</div>
</section>
``` 
**Question:** Is this as performant as the following?
```
<div *mobxAutorun>
  <section class="longListOfCountriesAndStatesAndCities">
    <div *ngFor="let obj of allCountriesStatesCitiesInTheWorld">...</div>
  </section>

  <section class="longListOfUsersLikeReallyLong">
    <div *ngFor="let user of allFacebookUsersInTheWholeSystem">...</div>
  </section>
</div>
```
Here is why I believed there to be a difference in performance:
**Hypothesis:** whenever there is change in any of the variables of the "autorun-zone", the whole zone will be re-calculated and re-rendered.
By splitting up these autorun-zones, I had hoped to prevent this.
I had hoped that if a new city would be added to the list of cities, then just that section is being re-rendered.
Likewise, if there was a new user added to the list of users, then just the user section is being re-rendered.

Can you confirm or deny this hypothesis and/or simply clear up this confusion?

**Comment by SerkanSipahi** [comment] 2018-01-29 16:42
@adamkleingit @SvenSchoene 
After separated the todo-app into [section](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html#L8) and [footer](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html#L21) components it still hasn't cleared up for me but after packing the [count](https://github.com/mobxjs/mobx-angular/blob/master/example/todos/src/app/app.component.html#L22-L24) also into a component everything has cleared up  and you could see how mobx-angular works. 

So, when i added a todo, only a [change detection](https://github.com/mobxjs/mobx-angular/blob/master/lib/directives/mobx-autorun.directive.ts#L40-L41) was triggered for `section` and `count`(component) and not for the `footer`(component)(because there was no change)!

I will make tomorrow a pull-request for code and README.md (with some clarification) :)

**Comment by returnlytom** [comment] 2018-01-29 18:04
Thanks @SerkanSipahi for clarifying this, looking forward to the PR. This has also caused me some confusion in the past.

**Comment by SerkanSipahi** [comment] 2018-02-01 09:16
@returnlytom do you have any idea how can i create a PR over the command line mobx-angular?

**Comment by returnlytom** [comment] 2018-02-01 09:33
@SerkanSipahi Maybe you can use `hub`?

https://hub.github.com/

**Comment by SerkanSipahi** [comment] 2018-02-01 15:42
@returnlytom i think this is it what im looking for https://hub.github.com/#As a contributor to open-source , thank your :)

**Comment by SerkanSipahi** [comment] 2018-02-03 11:09
@adamkleingit  @returnlytom @SvenSchoene please see PR https://github.com/mobxjs/mobx-angular/pull/63

**Comment by SerkanSipahi** [comment] 2018-02-05 12:17
thanks for merging https://github.com/mobxjs/mobx-angular/pull/63

**Comment by SvenSchoene** [comment] 2018-02-05 12:31
Why is this closed? My question above still stands.

**Comment by SerkanSipahi** [comment] 2018-02-05 13:18
@SvenSchoene right :)

**Comment by adamkleingit** [comment] 2018-02-06 10:10
@SvenSchoene can you reproduce in a plunkr?
Basically if you have 2 *mobxAutoruns then each one should run independently.
In the given example - if the action that initiates adding a new city is in the same component, then Angular will run CD on the entire component anyway. If it's in a separate component then CD should run only on the part that uses the changed data.

P.S. I'm closing the issue because there's no bug to fix here but feel free to continue the discussion

**Closed by adamkleingit** 2018-02-06 10:10 UTC

**Comment by SvenSchoene** [comment] 2018-02-06 10:14
Thanks for the input.
Under that consideration closing this issue is obviously correct, I agree.

I'll think about this issue and will try to come up with something reproducible.
