### ISSUE TITLE
fail to run with angular 9

### ISSUE THREAD

**Issue by ronentidhar** [mobxjs/mobx-angular#116] opened 2020-02-12 20:57 UTC
ng serve
0% compiling
Compiling @angular/core : module as esm5

Compiling @angular/common : module as esm5

Compiling @angular/platform-browser : module as esm5

Compiling @angular/platform-browser-dynamic : module as esm5

Compiling angular-tree-component : module as esm5

chunk {main} main.js, main.js.map (main) 1.96 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 660 bytes [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 433 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 21.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-02-12T20:54:39.077Z - Hash: 24936f4fa038e3738fa4 - Time: 12665ms

**ERROR in Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
node_modules/mobx-angular/dist/mobx-angular.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

8 export declare class MobxAngularModule {**

**Comment by ronentidhar** [comment] 2020-02-12 21:00
Same with es2015

ng serve
0% compiling
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling angular-tree-component : module as esm5

chunk {main} main.js, main.js.map (main) 1.96 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 660 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 21.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-02-12T20:59:29.537Z - Hash: bdb20b434969968c1c12 - Time: 9574ms

ERROR in Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
node_modules/mobx-angular/dist/mobx-angular.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

8 export declare class MobxAngularModule {

**Comment by kubk** [comment] 2020-02-12 22:34
Could you create a repo with reproduction? Angular 9 support was fixed recently: https://github.com/mobxjs/mobx-angular/issues/112

**Comment by Cpassimal** [comment] 2020-02-13 14:52
Same here

ERROR in Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
node_modules/mobx-angular/dist/mobx-angular.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

8 export declare class MobxAngularModule {

I just installed last version on npm, 8.5.4, and i checked on the node_modules/mobx-angular, the version 3.1.1 is indeed here.

**Comment by kubk** [comment] 2020-02-13 15:40
@Cpassimal Please read my comment above. A repro (on stackblitz or codesandbox) would be helpful.

**Comment by kubk** [comment] 2020-02-13 15:51
Here is an example with Angular 9 and Mobx working together: https://stackblitz.com/edit/angular-gd1ybt?file=package.json

**Comment by Cpassimal** [comment] 2020-02-14 09:40
I was having this issue using angular-tree-component in the version 8.5.4, 8.5.5 solved the problem.

**Comment by Mattnmoore** [comment] 2020-02-14 16:26
I'm also running into this issue with Angular 9 with Ivy enabled. 3.0.3 works with Ivy disabled. 

> I was having this issue using angular-tree-component in the version 8.5.4, 8.5.5 solved the problem.

It looks like they manually pulled in mobx-angular and made changes to it to get it to work with their library.

**Comment by PhilippRoessner** [comment] 2020-02-17 07:58
I have also trouble to get my App upgraded to angular 9. I get the following message when I build:

> ERROR in ./node_modules/mobx-angular/dist/directives/mobx-reaction.directive.js 35:16-24
"export 'Renderer' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
    at C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\Compiler.js:672:17
    at _done (eval at create (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:36:22)
    at C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\AIS\Versions\4\4.15\AISweb\dataConnect.AISportal\ClientApp\node_modules\webpack\lib\Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
 @ ./node_modules/mobx-angular/dist/mobx-angular.js
 @ ./node_modules/angular-tree-component/dist/angular-tree-component.js
 @ ./libs/aiscommon/src/aiscommon.module.ts
 @ ./libs/aiscommon/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by adamkleingit** [comment] 2020-02-19 09:11
This was fixed in angular-tree-compoment version 8.5.6

**Closed by adamkleingit** 2020-02-19 09:11 UTC
